server:
  port: 8088

spring:
  datasource:
    url: jdbc:h2:~/aplicativo;DB_CLOSE_ON_EXIT=FALSE
    username: fiap
    password: fiap
  h2:
    console:
      enabled: 'true'
      path: /h2-console


#spring:
#  datasource:
#    url: jdbc:mysql://localhost/test;DB_CLOSE_ON_EXIT=FALSE
#    username: fiap
#    password: fiap
#  batch:
#    initialize-schema: always
#    schema: classpath:schema-all.sql
